version: "3"
services:
  redis:
    image: "redis:latest"
  server:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "4010:4010"
      - "8089:8089"
